### PR TITLE
Dump EPSG codes/definitions from latest PROJ

### PR DESCRIPTION
**Pull request by Saijin-Naib**
These EPSG definitions are dumped from the latest/current upstream PROJ library using the included projdump.py script provided by mikewatt via gis.stackexchange.com

These new definitions do not include the towgs84 attribute, but apparently that is recommended against at this point.

Please let me know if this works for your intended purpose!

Thanks.

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks!

**Comment by Saijin-Naib** [comment]
Wait, this actually worked?!

**Comment by pierotofy** [comment]
We'll find out. :)

**Comment by pierotofy** [comment]
Welp, I don't think this is going to work out of the box, unfortunately; seeing lots of issues with reprojections and swapped coordinates in the X/Y, even after updating proj4js to the latest.

Updated branch with changes https://github.com/uav4geo/GCPEditorPro/tree/proj

**Comment by Saijin-Naib** [comment]
Ah, that's a bummer, but not unexpected. I figured I'm missing something.

Is it the format of how I exported the strings, or are we not lucky enough that it's something that easy?

**Comment by pierotofy** [comment]
I'll be honest, I haven't followed the updates to proj to tell what could have gone wrong and what needs to be done to fix it.

**Comment by Saijin-Naib** [comment]
> I'll be honest, I haven't followed the updates to proj to tell what could have gone wrong and what needs to be done to fix it.

Do you think it's because PROJ4JS relies upon the towgs84 transform, which is completely lacking in what I dumped?

**Comment by pierotofy** [comment]
It's probably related to that, yes. This document has an in-depth description of the changes, but will take some reading to digest it: https://www.icsm.gov.au/sites/default/files/North%20Road%20Handling%20GDA2020%20within%20Geospatial%20Software%20Development.pdf

**Comment by pierotofy** [comment]
Part of the problem is that I'm pretty sure proj4.js does not support the new definitions. We could still expand the available EPSG database, but we need to use proj4 definitions (the older ones).

**Comment by Saijin-Naib** [comment]
Alright, I think that limits us to PROJ5. Hopefully it has more definitions than what PROJ4JS had before. I'll try that shortly.

Yeah, looks like PROJ6 deprecated the towgs84, and no longer enforced axis order.

PROJ5 looks like it would support these newer CRSs, but shouldn't give us issues with axis order and towgs84. I think.

**Comment by Saijin-Naib** [comment]
So, my current understanding is this:
We'd need pyproj==v1.9.6rel to interface with PROJ 5.2.0

I've compiled/installed both locally, but the projdump script doesn't work with this version of pyproj as it lacks the class to query the database.

However, the PROJ documentation seems to indicate that it has a method to just dump the EPSG code to a proj string easily.
https://pyproj4.github.io/pyproj/v1.9.6rel/pyproj-module.html

I don't know how to wire this up so that the script asks PROJ 5.2.0 for all the EPSG codes, and then subsequently dumps them to JSON as PROJ4 strings.

**Pull request merged**
